# careers
human_careers={
                1:"apothecary",
                2:"engineer",
                3:"lawyer",
                4:"nun",
                5:"nun",
                6:"physician",
                7:"priest",
                8:"priest",
                9:"priest",
                10:"priest",
                11:"priest",
                12:"scholar",
                13:"scholar",
                14:"wizard",
                15:"agitator",
                16:"artisan",
                17:"artisan",
                18:"beggar",
                19:"beggar",
                20:"investigator",
                21:"merchant",
                22:"rat catcher",
                23:"rat catcher",
                24:"townsman",
                25:"townsman",
                26:"townsman",
                27:"watchman",
                28:"advisor",
                29:"artist",
                30:"duellist",
                31:"envoy",
                32:"noble",
                33:"servant",
                34:"servant",
                35:"servant",
                36:"spy",
                37:"warden",
                38:"bailiff",
                39:"hedge witch",
                40:"herbalist",
                41:"hunter",
                42:"hunter",
                43:"miner",
                44:"mystic",
                45:"scout",
                46:"villager",
                47:"villager",
                48:"villager",
                49:"villager",
                50:"villager",
                51:"bounty hunter",
                52:"coachman",
                53:"entertainer",
                54:"entertainer",
                55:"flagellant",
                56:"flagellant",
                57:"messenger",
                58:"pedlar",
                59:"road warden",
                60:"witch hunter",
                61:"boatman",
                62:"boatman",
                63:"huffer",
                64:"riverwarden",
                65:"riverwarden",
                66:"riverwoman",
                67:"riverwoman",
                68:"riverwoman",
                69:"seaman",
                70:"seaman",
                71:"smuggler",
                72:"stevedore",
                73:"stevedore",
                74:"wrecker",
                75:"bawd",
                76:"bawd",
                77:"charlatan",
                78:"fence",
                79:"grave robber",
                80:"outlaw",
                81:"outlaw",
                82:"outlaw",
                83:"outlaw",
                84:"racketeer",
                85:"thief",
                86:"thief",
                87:"thief",
                88:"witch",
                89:"cavalryman",
                90:"cavalryman",
                91:"guard",
                92:"guard",
                93:"knight",
                94:"pit fighter",
                95:"protagonist",
                96:"soldier",
                97:"soldier",
                98:"soldier",
                99:"soldier",
                100:"warrior priest"
            }
dwarf_careers={
                1:"apothecary",
                2:"engineer",
                3:"engineer",
                4:"engineer",
                5:"lawyer",
                6:"lawyer",
                7:"physician",
                8:"scholar",
                9:"scholar",
                10:"agitator",
                11:"agitator",
                12:"artisan",
                13:"artisan",
                14:"artisan",
                15:"artisan",
                16:"artisan",
                17:"artisan",
                18:"beggar",
                19:"investigator",
                20:"investigator",
                21:"merchant",
                22:"merchant",
                23:"merchant",
                24:"merchant",
                25:"rat catcher",
                26:"townsman",
                27:"townsman",
                28:"townsman",
                29:"townsman",
                30:"townsman",
                31:"townsman",
                32:"watchman",
                33:"watchman",
                34:"watchman",
                35:"advisor",
                36:"advisor",
                37:"artist",
                38:"duellist",
                39:"envoy",
                40:"envoy",
                41:"noble",
                42:"servant",
                43:"spy",
                44:"warden",
                45:"warden",
                46:"bailiff",
                47:"bailiff",
                48:"hunter",
                49:"hunter",
                50:"miner",
                51:"miner",
                52:"miner",
                53:"miner",
                54:"miner",
                55:"scout",
                56:"villager",
                57:"bounty hunter",
                58:"bounty hunter",
                59:"bounty hunter",
                60:"bounty hunter",
                61:"coachman",
                62:"entertainer",
                63:"entertainer",
                64:"messenger",
                65:"messenger",
                66:"pedlar",
                67:"pedlar",
                68:"boatman",
                69:"boatman",
                70:"huffer",
                71:"riverwoman",
                72:"riverwoman",
                73:"seaman",
                74:"smuggler",
                75:"smuggler",
                76:"stevedore",
                77:"stevedore",
                78:"wrecker",
                79:"fence",
                80:"outlaw",
                81:"outlaw",
                82:"outlaw",
                83:"racketeer",
                84:"thief",
                85:"guard",
                86:"guard",
                87:"guard",
                88:"pit figher",
                89:"pit figher",
                90:"pit figher",
                91:"protagonist",
                92:"protagonist",
                93:"protagonist",
                94:"soldier",
                95:"soldier",
                96:"soldier",
                97:"slayer",
                98:"slayer",
                99:"slayer",
                100:"slayer"
            }
halfling_careers={
                1:"apothecary",
                2:"engineer",
                3:"lawyer",
                4:"lawyer",
                5:"physician",
                6:"physician",
                7:"scholar",
                8:"scholar",
                9:"agitator",
                10:"agitator",
                11:"artisan",
                12:"artisan",
                13:"artisan",
                14:"artisan",
                15:"artisan",
                16:"beggar",
                17:"beggar",
                18:"beggar",
                19:"beggar",
                20:"investigator",
                21:"investigator",
                22:"merchant",
                23:"merchant",
                24:"merchant",
                25:"merchant",
                26:"rat catcher",
                27:"rat catcher",
                28:"rat catcher",
                29:"townsman",
                30:"townsman",
                31:"townsman",
                32:"watchman",
                33:"watchman",
                34:"advisor",
                35:"artist",
                36:"artist",
                37:"envoy",
                38:"servant",
                39:"servant",
                40:"servant",
                41:"servant",
                42:"servant",
                43:"servant",
                44:"spy",
                45:"warden",
                46:"warden",
                47:"bailiff",
                48:"herbalist",
                49:"herbalist",
                50:"herbalist",
                51:"hunter",
                52:"hunter",
                53:"miner",
                54:"scout",
                55:"villager",
                56:"villager",
                57:"villager",
                58:"bounty hunter",
                59:"coachman",
                60:"coachman",
                61:"entertainer",
                62:"entertainer",
                63:"entertainer",
                64:"messenger",
                65:"messenger",
                66:"pedlar",
                67:"pedlar",
                68:"road warden",
                69:"boatman",
                70:"huffer",
                71:"riverwarden",
                72:"riverwoman",
                73:"riverwoman",
                74:"riverwoman",
                75:"seaman",
                76:"smuggler",
                77:"smuggler",
                78:"smuggler",
                79:"smuggler",
                80:"stevedore",
                81:"stevedore",
                82:"stevedore",
                83:"bawd",
                84:"bawd",
                85:"bawd",
                86:"charlatan",
                87:"fence",
                88:"grave robber",
                89:"outlaw",
                90:"racketeer",
                91:"thief",
                92:"thief",
                93:"thief",
                94:"thief",
                95:"guard",
                96:"guard",
                97:"pit fighter",
                98:"soldier",
                99:"soldier",
                100:"soldier"
            }
highelf_careers={
                1:"apothecary",
                2:"apothecary",
                3:"lawyer",
                4:"lawyer",
                5:"lawyer",
                6:"lawyer",
                7:"physician",
                8:"physician",
                9:"scholar",
                10:"scholar",
                11:"scholar",
                12:"scholar",
                13:"wizard",
                14:"wizard",
                15:"wizard",
                16:"wizard",
                17:"artisan",
                18:"artisan",
                19:"artisan",
                20:"investigator",
                21:"investigator",
                22:"merchant",
                23:"merchant",
                24:"merchant",
                25:"merchant",
                26:"merchant",
                27:"townsman",
                28:"townsman",
                29:"watchman",
                30:"advisor",
                31:"advisor",
                32:"artist",
                33:"duellist",
                34:"duellist",
                35:"envoy",
                36:"envoy",
                37:"envoy",
                38:"noble",
                39:"noble",
                40:"noble",
                41:"spy",
                42:"spy",
                43:"spy",
                44:"warden",
                45:"warden",
                46:"herbalist",
                47:"herbalist",
                48:"hunter",
                49:"hunter",
                50:"hunter",
                51:"scout",
                52:"scout",
                53:"scout",
                54:"scout",
                55:"scout",
                56:"scout",
                57:"bounty hunter",
                58:"bounty hunter",
                59:"bounty hunter",
                60:"entertainer",
                61:"entertainer",
                62:"entertainer",
                63:"messenger",
                64:"boatman",
                65:"seaman",
                66:"seaman",
                67:"seaman",
                68:"seaman",
                69:"seaman",
                70:"seaman",
                71:"seaman",
                72:"seaman",
                73:"seaman",
                74:"seaman",
                75:"seaman",
                76:"seaman",
                77:"seaman",
                78:"seaman",
                79:"seaman",
                80:"smuggler",
                81:"bawd",
                82:"bawd",
                83:"charlatan",
                84:"charlatan",
                85:"charlatan",
                86:"outlaw",
                87:"outlaw",
                88:"outlaw",
                89:"cavalryman",
                90:"cavalryman",
                91:"cavalryman",
                92:"cavalryman",
                93:"guard",
                94:"guard",
                95:"knight",
                96:"pit fighter",
                97:"pit fighter",
                98:"protagonist",
                99:"soldier",
                100:"soldier"
            }
woodelf_careers={
                1:"scholar",
                2:"wizard",
                3:"wizard",
                4:"wizard",
                5:"wizard",
                6:"artisan",
                7:"artisan",
                8:"artisan",
                9:"artisan",
                10:"artisan",
                11:"advisor",
                12:"advisor",
                13:"advisor",
                14:"advisor",
                15:"artist",
                16:"artist",
                17:"artist",
                18:"artist",
                19:"envoy",
                20:"envoy",
                21:"envoy",
                22:"envoy",
                23:"envoy",
                24:"envoy",
                25:"envoy",
                26:"noble",
                27:"noble",
                28:"noble",
                29:"noble",
                30:"noble",
                31:"noble",
                32:"spy",
                33:"spy",
                34:"spy",
                35:"spy",
                36:"herbalist",
                37:"herbalist",
                38:"herbalist",
                39:"herbalist",
                40:"herbalist",
                41:"herbalist",
                42:"herbalist",
                43:"hunter",
                44:"hunter",
                45:"hunter",
                46:"hunter",
                47:"hunter",
                48:"hunter",
                49:"hunter",
                50:"hunter",
                51:"hunter",
                52:"hunter",
                53:"mystic",
                54:"mystic",
                55:"mystic",
                56:"mystic",
                57:"messenger",
                58:"scout",
                59:"scout",
                60:"scout",
                61:"scout",
                62:"scout",
                63:"scout",
                64:"scout",
                65:"scout",
                66:"scout",
                67:"scout",
                68:"scout",
                69:"bounty hunter",
                70:"bounty hunter",
                71:"entertainer",
                72:"entertainer",
                73:"entertainer",
                74:"entertainer",
                75:"entertainer",
                76:"messenger",
                77:"messenger",
                78:"messenger",
                79:"wrecker",
                80:"outlaw",
                81:"outlaw",
                82:"outlaw",
                83:"outlaw",
                84:"outlaw",
                85:"outlaw",
                86:"cavalryman",
                87:"cavalryman",
                88:"cavalryman",
                89:"cavalryman",
                90:"cavalryman",
                91:"guard",
                92:"guard",
                93:"knight",
                94:"knight",
                95:"pit fighter",
                96:"pit fighter",
                97:"soldier",
                98:"soldier",
                99:"soldier",
                100:"soldier"
            }

# class
academics = ["apothecary", "engineer", "lawyer", "nun", "physician", "priest", "scholar", "wizard"]
burghers = ["agitator", "artisan", "beggar", "investigator", "merchant", "rat catcher", "townsman", "watchman"]
courtiers = ["advisor", "artist", "duelist", "envoy", "noble", "servant", "spy", "warden"]
peasants = ["bailiff", "hedge witch", "herbalist", "hunter", "miner", "mystic", "scout", "villager"]
rangers = ["bounty hunter", "coachman", "entertainer", "flagellant", "messenger", "pedlar", "road warden", "witch hunter"]
riverfolk = ["boatman", "huffer", "riverwarden", "riverwoman", "seaman", "smuggler", "stevedore", "wrecker"]
rogues = ["bawd", "charlatan", "fence", "grave robber", "outlaw", "racketeer", "theif", "witch"]
warriors = ["cavalryman", "guard", "knight", "pit fighter", "protagonist", "soldier", "slayer", "warrior priest"]

# names
male_reiklander = ["Aimar", "Askan", "Gerlach", "Rudolf", "Elmer", 
                   "Siegfried", "Hans", "Wilmer", "Helmer", "Helmut", 
                   "Wilbur", "Bruno", "Leonhard", "Lambert", "Reinhard", 
                   "Gotthard", "Ludwig", "Otto", "Dagobert", "Theobald", 
                   "Ralf", "Rolf", "Friedrich", "Dieter", "Adolf", 
                   "Heinrich", "Ralf"]

female_reiklander = ["Clementia", "Erika", "Fryke", "Frederike", 
                     "Gerthrud", "Helga", "Marieke", "Siegfreda", 
                     "Frieda", "Ulrika", "Wilhelmina", "Liebtrud", 
                     "Saskia", "Hildegard", "Hallgerd", "Ebba", "Hulda", 
                     "Yvonne", "Charlotte", "Inge", "Kajsa", "Kirsa", 
                     "Geraldine"]

reiklander_surname = ["Schaffenberger", "Adolphus", "Auerswalder", 
                      "Wissenlander", "Averlander", "Baumer",
                      "Autlermann", "Nordlander", "Damstadter",
                      "Eshermann", "Esselmann", "Breuer", 
                      "Bredermann", "Dasselmann", "Diermar",
                      "Donatus", "Eilhardt", "Ehrhard", 
                      "Dunkelberg", "Erasmus", "Gustavus", 
                      "Hergiger", "Henroth", "Hasselmann",
                      "Hausier", "Hahnbrandt", "Gundersohn",
                      "Heffengenger", "Heidmann", "Heinrich",
                      "Jaeger", "Bauer", "Hausier", 
                      "Hetzer", "Horst", "Feldtmann", 
                      "Feldt", "Garmann", "Frohlich", 
                      "Gisel", "Grenz", "Grundenburger", 
                      "Heinz", "Geldt", "Klein"]